[package]
name = "kappa_coder"
version = "0.1.0"
edition = "2024"

[dependencies]
data_model = { path = "../../KappaLibrary/data_model" }
processor_engine = { path = "../../KappaLibrary/processor_engine" }
libloading = "0.9.0"
